version: 1.0
bind: 0.0.0.0:9412
logLevel: info
mongodb:
  uri: mongodb://localhost:27017
  connectionTimeout: 3
  maxConnection: 3
  defaultInterval: 5
metrics:
- name: myapp_example_simplevalue_total
  type: gauge #Can also be empty, the default is gauge
  help: 'Simple gauge metric'
  value: total
  overrideEmpty: true # if an empty result set is returned..
  emptyValue: 0       # create a metric with value 0
  labels: []
  mode: pull
  cache: 0
  constLabels:
    region: eu-central-1
  database: mydb
  collection: objects
  pipeline: |
    [
      {"$count":"total"}
    ]
- name: myapp_example_processes_total
  type: gauge
  help: 'The total number of processes in a job queue'
  value: total
  mode: pull
  labels: [type,status]
  constLabels: {}
  database: mydb
  collection: queue
  pipeline: |
    [
      {"$group": {
        "_id":{"status":"$status","name":"$class"},
        "total":{"$sum":1}
      }},
      {"$project":{
        "_id":0,
        "type":"$_id.name",
        "total":"$total",
        "status": {
          "$switch": {
              "branches": [
                 { "case": { "$eq": ["$_id.status", 0] }, "then": "waiting" },
                 { "case": { "$eq": ["$_id.status", 1] }, "then": "postponed" },
                 { "case": { "$eq": ["$_id.status", 2] }, "then": "processing" },
                 { "case": { "$eq": ["$_id.status", 3] }, "then": "done" },
                 { "case": { "$eq": ["$_id.status", 4] }, "then": "failed" },
                 { "case": { "$eq": ["$_id.status", 5] }, "then": "canceled" },
                 { "case": { "$eq": ["$_id.status", 6] }, "then": "timeout" }
              ],
              "default": "unknown"
          }}
      }}
    ]
- name: myapp_events_total
  type: gauge
  help: 'The total number of events (created 1h ago or newer)'
  value: count
  mode: pull
  labels: [type]
  constLabels: {}
  database: mydb
  collection: events
  # Note $$NOW is only supported in MongoDB >= 4.2
  pipeline: |
    [
      { "$sort": { "created": -1 }},
      {"$limit": 100000},
      {"$match":{
        "$expr": {
          "$gte": [
            "$created",
            {
              "$subtract": ["$$NOW", 3600000]
            }
          ]
        }
      }},
      {"$group": {
        "_id":{"type":"$type"},
        "count":{"$sum":1}
      }},
      {"$project":{
        "_id":0,
        "type":"$_id.type",
        "count":"$count"
      }}
    ]
