apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: mongodb-query-exporter

images:
- name: raffis/mongodb-query-exporter:latest
  newTag: 2.0.1
