{{- if not .Values.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-mongodb-query-exporter.secretName" . }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-mongodb-query-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "prometheus-mongodb-query-exporter.chart" . }}
type: Opaque
data:
  {{- if .Values.mongodb }}
  {{- range $key, $value := .Values.mongodb }}
    MDBEXPORTER_SERVER_{{ $key }}_MONGODB_URI: "{{ $value | b64enc }}"
  {{- end }}
  {{- end }}
{{- end -}}
