name: Chart
on: push

jobs:
  chart:
    name: Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run helm lint
        id: lint
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint chart/prometheus-mongodb-query-exporter
