name: pr-trivy
on: pull_request

permissions: {}

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Trivy fs scan
        uses: aquasecurity/trivy-action@2297a1b967ecc05ba2285eb6af56ab4da554ecae # 0.14.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
